FROM python:3.8
EXPOSE 3000
USER root


RUN pip install -U pip
RUN pip install -U setuptools

RUN pip install  pandas
RUN pip install  numpy
RUN pip install  sqlalchemy
RUN pip install  ptvsd
